name: Build exe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Windows işletim sistemini seç

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      run: |
        curl -sS -o python.zip https://github.com/actions/python-versions/releases/download/3.9.0-96741/python-3.9.0-win32-x86.zip
        tar -xzf python.zip -C $RUNNER_TOOL_CACHE

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build exe
      run: |
        pip install cx_Freeze
        python setup.py build

    - name: Upload exe
      uses: actions/upload-artifact@v2
      with:
        name: your_script
        path: build/exe.win32-3.9/mami.exe
