name: Build exe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Windows işletim sistemini seç

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.0-win32-x86

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build exe
      run: |
        pip install cx_Freeze
        python setup.py build

    - name: Upload exe
      uses: actions/upload-artifact@v2
      with:
        name: your_script
        path: build/exe.win32-3.9/mami.exe
